/**
 * Detector de vídeos gerados por IA
 * Identifica vídeos que provavelmente foram criados por inteligência artificial
 */

import { ViralVideo } from '@/app/types';

/**
 * Palavras-chave e padrões que indicam vídeo gerado por IA
 */
const AI_INDICATORS = {
  // Palavras-chave no título
  titleKeywords: [
    'ai generated',
    'artificial intelligence',
    'synthetic',
    'deepfake',
    'automated',
    'machine learning',
    'neural network',
    'generated by ai',
    'ai created',
    'ai made',
    'computer generated',
    'virtual',
    'simulated',
    'gerado por ia',
    'inteligência artificial',
    'sintético',
    'automatizado',
    'criado por ia',
    'feito por ia',
    'gerado automaticamente',
  ],
  
  // Palavras-chave na descrição
  descriptionKeywords: [
    'this video was generated',
    'created using ai',
    'ai technology',
    'generated content',
    'synthetic media',
    'deep learning',
    'este vídeo foi gerado',
    'criado usando ia',
    'tecnologia de ia',
    'conteúdo gerado',
    'mídia sintética',
  ],
  
  // Padrões suspeitos no nome do canal
  channelPatterns: [
    /ai\s*channel/i,
    /bot\s*channel/i,
    /auto\s*generated/i,
    /synthetic\s*media/i,
    /machine\s*learning/i,
    /neural\s*network/i,
    /^[a-z0-9]{10,}$/i, // Nomes muito genéricos (só letras/números)
  ],
  
  // Padrões suspeitos no título
  titlePatterns: [
    /^[A-Z0-9\s]{20,}$/, // Títulos em caps lock muito longos
    /^\d+\.\s*[A-Z]/, // Títulos que começam com número seguido de ponto
    /\[.*ai.*\]/i, // Títulos com [AI] ou similar
    /\(.*generated.*\)/i, // Títulos com (generated) ou similar
  ],
};

/**
 * Verifica se um vídeo foi provavelmente gerado por IA
 */
export function isAIGenerated(video: ViralVideo): boolean {
  const title = (video.title || '').toLowerCase();
  const description = (video.description || '').toLowerCase();
  const channelTitle = (video.channelTitle || '').toLowerCase();
  
  let score = 0;
  
  // Verificar palavras-chave no título
  const titleMatches = AI_INDICATORS.titleKeywords.filter(keyword => 
    title.includes(keyword.toLowerCase())
  );
  score += titleMatches.length * 3; // Título tem peso maior
  
  // Verificar palavras-chave na descrição
  const descMatches = AI_INDICATORS.descriptionKeywords.filter(keyword => 
    description.includes(keyword.toLowerCase())
  );
  score += descMatches.length * 2;
  
  // Verificar padrões no nome do canal
  const channelMatches = AI_INDICATORS.channelPatterns.filter(pattern => 
    pattern.test(channelTitle)
  );
  score += channelMatches.length * 2;
  
  // Verificar padrões no título
  const titlePatternMatches = AI_INDICATORS.titlePatterns.filter(pattern => 
    pattern.test(video.title || '')
  );
  score += titlePatternMatches.length * 1;
  
  // Se score >= 3, provavelmente é gerado por IA
  return score >= 3;
}

/**
 * Filtra vídeos removendo os gerados por IA
 */
export function filterAIGenerated(videos: ViralVideo[], excludeAI: boolean): ViralVideo[] {
  if (!excludeAI) {
    return videos;
  }
  
  const before = videos.length;
  const filtered = videos.filter(video => !isAIGenerated(video));
  const removed = before - filtered.length;
  
  if (removed > 0) {
    console.log(`🤖 Filtro de IA: ${before} → ${filtered.length} vídeos (${removed} vídeos de IA removidos)`);
  }
  
  return filtered;
}

